### PR TITLE
Updating README to add note about it's use in Phoenix.

### PR DESCRIPTION
**Pull request by leighhalliday**
I ran into some difficulty using this plug because it wasn't being invoked, but I was instead receiving 404s. After chatting with Chris McCord he let me know that pipelines are only invoked for matched routes. By adding options routes, it would correctly call the pipeline and therefore the CORSPlug plug.

I just wanted to add that to the README as it took me a little while to figure out!

### CODE REVIEW

**Comment by mschae** [comment]
Good call, thanks!

**Comment by mschae** [comment]
This relates to all PRs: For some reason I haven't received any emails from PRs in this repo. I apologise for the super late reply/merge!

**Comment by mschae** [comment]
Can you fix the merge conflicts please?

**Comment by leighhalliday** [comment]
Done! :)

**Comment by mschae** [comment]
Jeez what took you so long!? :)

Thanks

**Pull request merged**
